Allows following http links and links with #ids
bddean/emacs-ereader pull request #11
Opened 2017-04-16 01:17 UTC by sudarshang

EPUB allows links to external sites as well as links of the form url#id, where id refers to the identifier of the div that is the target of the link. This change opens the http links in an external browser. Links of the form url#id are resolved to the url and the id is ignored.

2017-04-16 03:09 UTC, bddean requested changes
Thanks! Just a small question and a style nit before lgtm

2017-04-16 03:09 UTC, bddean commented on ereader.el
> +  ))
Nit: join to previous line, for style consistency

2017-04-16 03:09 UTC, bddean commented on ereader.el
> +                   (get-text-property (point) 'ereader-target) "#")))))
Why ignore the id? Shouldn't the browser open the full url, including the hash?

2017-04-17 11:18 UTC, sudarshang commented
Do let me know if this looks OK. For some reason github shows that you have 'requested changes' on the latest PR, but I am unable to see those by clicking on the 'See review' link.

2017-04-17 13:03 UTC, bddean approved these changes

2017-04-17 13:03 UTC, bddean commented
Thanks, lgtm, merging

2017-04-17 13:03 UTC, merged